kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /tmp/kind-node-disk
        containerPath: /var/lib/containerd
  - role: worker
    extraMounts:
      - hostPath: /tmp/kind-node-disk1
        containerPath: /var/lib/containerd
  - role: worker
    extraMounts:
      - hostPath: /tmp/kind-node-disk2
        containerPath: /var/lib/containerd
  - role: worker
    extraMounts:
      - hostPath: /tmp/kind-node-disk3
        containerPath: /var/lib/containerd
