name: Kubernetes

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  PYTHON_VERSION: 3.9
  TPCH_SCALING_FACTOR: "1"
  TPCH_TEST_PARTITIONS: "1"
  TPCH_DATA_PATH: "data"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./k8s/Dockerfile
          tags: username/repository:tag
