name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  PYTHON_VERSION: 3.9
  TPCH_SCALING_FACTOR: "1"
  TPCH_TEST_PARTITIONS: "1"
  TPCH_DATA_PATH: "data"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install protobuf compiler
        shell: bash
        run: sudo apt-get install protobuf-compiler
      - name: Build Rust code
        run: cargo build --verbose
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tpch/requirements.txt
      - name: Generate test data
        run: |
          ./scripts/gen-test-data.sh
      - name: Run tests
        run: cargo test --verbose
